from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class AssetCatalogEntry:
    symbol: str
    name: str
    market: str
    asset_class: str
    currency: str
    provider: str
    summary: str
    sector: str | None = None
    yahoo_symbol: str | None = None
    binance_symbol: str | None = None
    is_us_equity: bool = False
    searchable: bool = True


ASSET_CATALOG: dict[str, AssetCatalogEntry] = {
    "AAPL": AssetCatalogEntry(
        symbol="AAPL",
        name="Apple Inc.",
        market="NASDAQ",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="大盘科技龙头，现金流稳健，适合作为首页和资产页默认深度样本。",
        sector="Technology Hardware",
        yahoo_symbol="AAPL",
        is_us_equity=True,
    ),
    "SPY": AssetCatalogEntry(
        symbol="SPY",
        name="SPDR S&P 500 ETF",
        market="NYSE Arca",
        asset_class="etf",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="全局风险偏好与组合收益对比的默认基准。",
        sector="ETF",
        yahoo_symbol="SPY",
    ),
    "NVDA": AssetCatalogEntry(
        symbol="NVDA",
        name="NVIDIA Corporation",
        market="NASDAQ",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="高波动成长股，用于验证筛选、行情和基本面状态差异。",
        sector="Semiconductors",
        yahoo_symbol="NVDA",
        is_us_equity=True,
    ),
    "MSFT": AssetCatalogEntry(
        symbol="MSFT",
        name="Microsoft Corporation",
        market="NASDAQ",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="Large-cap software compounder for the expanded quality screener universe.",
        sector="Software",
        yahoo_symbol="MSFT",
        is_us_equity=True,
    ),
    "GOOGL": AssetCatalogEntry(
        symbol="GOOGL",
        name="Alphabet Inc. Class A",
        market="NASDAQ",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="Cash-generative internet platform used in the expanded equity screeners.",
        sector="Interactive Media",
        yahoo_symbol="GOOGL",
        is_us_equity=True,
    ),
    "AMZN": AssetCatalogEntry(
        symbol="AMZN",
        name="Amazon.com, Inc.",
        market="NASDAQ",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="High-liquidity growth name retained in the controlled expansion universe.",
        sector="Consumer Cyclical",
        yahoo_symbol="AMZN",
        is_us_equity=True,
    ),
    "META": AssetCatalogEntry(
        symbol="META",
        name="Meta Platforms, Inc.",
        market="NASDAQ",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="Platform-scale advertiser kept in the controlled expansion universe.",
        sector="Interactive Media",
        yahoo_symbol="META",
        is_us_equity=True,
    ),
    "COST": AssetCatalogEntry(
        symbol="COST",
        name="Costco Wholesale Corporation",
        market="NASDAQ",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="Defensive quality retailer used to balance the expanded equity universe.",
        sector="Consumer Defensive",
        yahoo_symbol="COST",
        is_us_equity=True,
    ),
    "LLY": AssetCatalogEntry(
        symbol="LLY",
        name="Eli Lilly and Company",
        market="NYSE",
        asset_class="equity",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="Healthcare quality compounder used in the expanded equity universe.",
        sector="Healthcare",
        yahoo_symbol="LLY",
        is_us_equity=True,
    ),
    "600519.SH": AssetCatalogEntry(
        symbol="600519.SH",
        name="Kweichow Moutai Co., Ltd.",
        market="Shanghai Stock Exchange",
        asset_class="equity",
        currency="CNY",
        provider="tushare",
        summary="Controlled A-share seed for China-market connector and research-template validation.",
        sector="Consumer Staples",
        yahoo_symbol="600519.SS",
    ),
    "000001.SZ": AssetCatalogEntry(
        symbol="000001.SZ",
        name="Ping An Bank Co., Ltd.",
        market="Shenzhen Stock Exchange",
        asset_class="equity",
        currency="CNY",
        provider="tushare",
        summary="Controlled Shenzhen A-share seed for read-only connector validation.",
        sector="Banking",
        yahoo_symbol="000001.SZ",
    ),
    "300750.SZ": AssetCatalogEntry(
        symbol="300750.SZ",
        name="Contemporary Amperex Technology Co., Ltd.",
        market="Shenzhen Stock Exchange",
        asset_class="equity",
        currency="CNY",
        provider="tushare",
        summary="Controlled ChiNext A-share seed for China-market research validation.",
        sector="Battery",
        yahoo_symbol="300750.SZ",
    ),
    "BTC/USDT": AssetCatalogEntry(
        symbol="BTC/USDT",
        name="Bitcoin / Tether",
        market="Binance",
        asset_class="crypto",
        currency="USDT",
        provider="ccxt:binance",
        summary="加密主轴标的，承接公开行情与 Binance 私有账户连接能力。",
        binance_symbol="BTCUSDT",
    ),
    "ETH/USDT": AssetCatalogEntry(
        symbol="ETH/USDT",
        name="Ethereum / Tether",
        market="Binance",
        asset_class="crypto",
        currency="USDT",
        provider="ccxt:binance",
        summary="Large-cap smart-contract benchmark kept in the controlled crypto universe.",
        binance_symbol="ETHUSDT",
    ),
    "BNB/USDT": AssetCatalogEntry(
        symbol="BNB/USDT",
        name="BNB / Tether",
        market="Binance",
        asset_class="crypto",
        currency="USDT",
        provider="ccxt:binance",
        summary="Exchange-led large-cap token kept in the controlled crypto universe.",
        binance_symbol="BNBUSDT",
    ),
    "SOL/USDT": AssetCatalogEntry(
        symbol="SOL/USDT",
        name="Solana / Tether",
        market="Binance",
        asset_class="crypto",
        currency="USDT",
        provider="ccxt:binance",
        summary="High-beta layer-one asset kept in the controlled crypto universe.",
        binance_symbol="SOLUSDT",
    ),
    "XRP/USDT": AssetCatalogEntry(
        symbol="XRP/USDT",
        name="XRP / Tether",
        market="Binance",
        asset_class="crypto",
        currency="USDT",
        provider="ccxt:binance",
        summary="Liquid payments token kept in the controlled crypto universe.",
        binance_symbol="XRPUSDT",
    ),
    "LINK/USDT": AssetCatalogEntry(
        symbol="LINK/USDT",
        name="Chainlink / Tether",
        market="Binance",
        asset_class="crypto",
        currency="USDT",
        provider="ccxt:binance",
        summary="Oracle infrastructure token kept in the controlled crypto universe.",
        binance_symbol="LINKUSDT",
    ),
    "DOGE/USDT": AssetCatalogEntry(
        symbol="DOGE/USDT",
        name="Dogecoin / Tether",
        market="Binance",
        asset_class="crypto",
        currency="USDT",
        provider="ccxt:binance",
        summary="High-liquidity retail beta token kept in the controlled crypto universe.",
        binance_symbol="DOGEUSDT",
    ),
    "QQQ": AssetCatalogEntry(
        symbol="QQQ",
        name="Invesco QQQ Trust",
        market="NASDAQ",
        asset_class="etf",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="纳指 100 风险偏好基准。",
        sector="ETF",
        yahoo_symbol="QQQ",
    ),
    "TQQQ": AssetCatalogEntry(
        symbol="TQQQ",
        name="ProShares UltraPro QQQ",
        market="NASDAQ",
        asset_class="etf",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="3x long Nasdaq 100 ETF for explicit high-beta Nasdaq exposure.",
        sector="Leveraged ETF",
        yahoo_symbol="TQQQ",
    ),
    "DXY": AssetCatalogEntry(
        symbol="DXY",
        name="US Dollar Index",
        market="ICE",
        asset_class="macro",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="美元强弱观察位。",
        yahoo_symbol="DX-Y.NYB",
        searchable=False,
    ),
    "US10Y": AssetCatalogEntry(
        symbol="US10Y",
        name="US 10Y Treasury Yield",
        market="CBOE",
        asset_class="macro",
        currency="USD",
        provider="openbb-fallback:yahoo",
        summary="10 年期美债收益率观察位。",
        yahoo_symbol="^TNX",
        searchable=False,
    ),
}

DEFAULT_WATCHLIST = ["AAPL", "SPY", "BTC/USDT", "NVDA"]

DEFAULT_SCREENERS = [
    {
        "key": "quality-equities",
        "title": "美股高质量现金流",
        "badge": "股票",
        "description": "优先锁定盈利稳定、现金流强、估值不过热的核心资产。",
        "filters": ["市值 > 100B", "FCF Margin > 15%", "ROE > 18%", "负债率 < 60%"],
        "asset_type": "equity",
        "hit_count": 14,
    },
    {
        "key": "growth-rebound",
        "title": "成长回撤修复",
        "badge": "股票",
        "description": "寻找景气赛道中跌深反弹、但基本面未破坏的品种。",
        "filters": ["52W 回撤 > 20%", "营收增长 > 18%", "毛利率 > 45%", "成交额提升"],
        "asset_type": "equity",
        "hit_count": 22,
    },
    {
        "key": "trend-crypto",
        "title": "高流动性趋势加密",
        "badge": "加密",
        "description": "偏短中线交易观察，强调流动性、成交量与趋势延续。",
        "filters": ["Binance 可交易", "24H Volume > 150M", "7D Change > 8%", "波动率 < 65%"],
        "asset_type": "crypto",
        "hit_count": 9,
    },
    {
        "key": "majors-crypto",
        "title": "强势主流币观察",
        "badge": "加密",
        "description": "聚焦市值靠前、叙事清晰、具备主流资金承接的币种。",
        "filters": ["市值 Top 25", "资金费率平稳", "周线新高附近", "现货深度良好"],
        "asset_type": "crypto",
        "hit_count": 7,
    },
]

PORTFOLIO_SUMMARY = {
    "total_value": "$1.28M",
    "daily_pnl": "+$12.4K",
    "benchmark": "SPY / BTC mix",
    "positions": 9,
}
